parameters:
    tebru_executioner.executor_factory.class: Tebru\Executioner\Factory\ExecutorFactory

services:
    tebru_executioner.executor_factory:
        alias: executor_factory
        class: %tebru_executioner.executor_factory.class%
