parameters:
    tebru_executioner.exponential_wait_strategy.class: Tebru\Executioner\Strategy\Wait\ExponentialWait
    tebru_executioner.fibonacci_wait_strategy.class: Tebru\Executioner\Strategy\Wait\FibonacciWait
    tebru_executioner.linear_wait_strategy.class: Tebru\Executioner\Strategy\Wait\LinearWait
    tebru_executioner.logarithmic_wait_strategy.class: Tebru\Executioner\Strategy\Wait\LogarithmicWait
    tebru_executioner.null_wait_strategy.class: Tebru\Executioner\Strategy\Wait\NullWait
    tebru_executioner.static_wait_strategy.class: Tebru\Executioner\Strategy\Wait\StaticWait
    tebru_executioner.attempt_bound_termination_strategy.class: Tebru\Executioner\Strategy\Termination\AttemptBoundStrategy
    tebru_executioner.single_attempt_termination_strategy.class: Tebru\Executioner\Strategy\Termination\SingleAttemptStrategy
    tebru_executioner.time_bound_termination_strategy.class: Tebru\Executioner\Strategy\Termination\TimeBoundStrategy

    tebru_executioner.exponential_wait_factory.class: Tebru\Executioner\Factory\WaitStrategy\ExponentialWaitFactory
    tebru_executioner.fibonacci_wait_factory.class: Tebru\Executioner\Factory\WaitStrategy\FibonacciWaitFactory
    tebru_executioner.linear_wait_factory.class: Tebru\Executioner\Factory\WaitStrategy\LinearWaitFactory
    tebru_executioner.logarithmic_wait_factory.class: Tebru\Executioner\Factory\WaitStrategy\LogarithmicWaitFactory
    tebru_executioner.null_wait_factory.class: Tebru\Executioner\Factory\WaitStrategy\NullWaitFactory
    tebru_executioner.static_wait_factory.class: Tebru\Executioner\Factory\WaitStrategy\StaticWaitFactory
    tebru_executioner.attempt_bound_termination_factory.class: Tebru\Executioner\Factory\TerminationStrategy\AttemptBoundFactory
    tebru_executioner.single_attempt_termination_factory.class: Tebru\Executioner\Factory\TerminationStrategy\SingleAttemptFactory
    tebru_executioner.time_bound_termination_factory.class: Tebru\Executioner\Factory\TerminationStrategy\TimeBoundFactory

    tebru_executioner.exception_logger_factory.class: Tebru\Executioner\Factory\ExceptionLoggerFactory
    
    tebru_executioner.executor.class: Tebru\Executioner\Executor
    tebru_executioner_wait_strategy.class: Tebru\Executioner\Strategy\WaitStrategy
    tebru_executioner_termination_strategy.class: Tebru\Executioner\Strategy\TerminationStrategy

services:
    tebru_executioner.null_logger:
        class: Psr\Log\NullLogger

    tebru_executioner.defaut_exception_logger:
        class: Tebru\Executioner\Logger\ExceptionLogger
        arguments: [@tebru_executioner.null_logger]
