parameters:
    tebru_executioner.executor_factory.class: Tebru\Executioner\Factory\ExecutorFactory
    tebru_executioner.executor.class: Tebru\Executioner\Executor

services:
    executor_factory: @tebru_executioner.executor_factory
    tebru_executioner.executor_factory:
        class: %tebru_executioner.executor_factory.class%
